# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# and comment for good luck
trigger:
- main

pr:
  branches:
    include:
      - main
      - master
      - rfrydrysek/*
      - herbertwaage/*

pool:
  vmImage: 'windows-latest'

jobs:
- job: HelloWorld
  steps:

  - script: echo Hello from Herbert
    displayName: 'Run a one-line script'
    